spring.application.name=keymanager

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5431/keymanagerdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:mysecretpass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:change-me-dev-only-secret-change-me}
jwt.access-token-expiration-ms=${JWT_EXPIRATION_MS:900000}